### ISSUE TITLE
Error: ESLint crashed: Unknown type Super

### ISSUE THREAD

**Issue by saadq** [roadhump/SublimeLinter-eslint#100]
Hi,

This plugin has been working perfectly for me until recently. For some reason, I'm getting an error that says `Error: ESLint crashed: Unknown type Super` at the top of a few files that use the `super()` command in React. If I get rid of the `super()` statement, the error changes to `Error: ESLint crashed: Unknown type ExportDefaultDeclaration`. I've tried looking through the FAQ, but I couldn't find a solution there.

What's weird is that I have no issues when I run `$ eslint Scramble.js` in the terminal. No errors are caused when I run it from the command line.

Here is a screenshot that shows my current issue:

<img width="1392" alt="screen shot 2015-10-26 at 7 33 41 pm" src="https://cloud.githubusercontent.com/assets/5678694/10745502/afda4e88-7c18-11e5-87be-431ad447f3f7.png">

**Comment by roadhump** [comment]
Hello, can you check debug output: Tools -> SublimeLinter -> Debug Mode and Ctrl+\` ? Also, are you sure you use the same global `eslint` on project as on command line?

**Comment by saadq** [comment]
Hey,

Here is my output:

    SublimeLinter: chdir not set or invalid, using /Users/saad/Projects/Cube Stats/client/js/components 
    SublimeLinter: eslint: Scramble.js ['/Users/saad/Projects/Cube Stats/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
    SublimeLinter: chdir not set or invalid, using /Users/saad/Projects/Cube Stats/client/js/components 
    SublimeLinter: eslint: Scramble.js ['/Users/saad/Projects/Cube Stats/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
    SublimeLinter: eslint output:
    Unknown node type Super.
    Error: Unknown node type Super.
        at Controller.traverse (/Users/saad/Projects/Cube Stats/node_modules/estraverse/estraverse.js:517:31)
        at EventEmitter.module.exports.api.verify (/Users/saad/Projects/Cube Stats/node_modules/eslint/lib/eslint.js:779:24)
        at processText (/Users/saad/Projects/Cube Stats/node_modules/eslint/lib/cli-engine.js:221:27)
        at CLIEngine.executeOnText (/Users/saad/Projects/Cube Stats/node_modules/eslint/lib/cli-engine.js:678:26)
        at Object.cli.execute (/Users/saad/Projects/Cube Stats/node_modules/eslint/lib/cli.js:159:36)
        at /Users/saad/Projects/Cube Stats/node_modules/eslint/bin/eslint.js:41:28
        at ConcatStream.<anonymous> (/Users/saad/Projects/Cube Stats/node_modules/concat-stream/index.js:36:43)
        at emitNone (events.js:72:20)
        at ConcatStream.emit (events.js:166:7)
        at finishMaybe (/Users/saad/Projects/Cube Stats/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14) 

I'm not sure what you mean about using the same global `eslint`, is there something I can do to check if they are the same?

**Comment by roadhump** [comment]
It looks like you use `eslint` which installed in your project, I can say it by path `/Users/saad/Projects/Cube Stats/node_modules/.bin/eslint` in your console. Can you run eslint by this path instead of global `eslint` and check output? Also, I can guess that, probably, you have outdated version of `eslint` in your project. Check versions of your local and global `eslint` instances.

**Comment by saadq** [comment]
You were right, I was using an outdated version in my local project. I had to remove my global `eslint` and all the `eslint` stuff from `/node_modules` and `/node_modules/.bin/` and reinstall it locally to get it to start working again. Thanks for the help!
