### ISSUE TITLE
Different file formats?

### ISSUE THREAD

**Issue by mrmartineau** [roadhump/SublimeLinter-eslint#110]
ESLint supports configuration files in [several formats](http://eslint.org/docs/user-guide/configuring#configuration-file-formats), not just `.eslintrc`, would it be possible for this plugin support them all?

**Comment by roadhump** [comment]
There is no hardcoded .eslintrc in plugin, so I suppose it already supports formats now. You can check and report if something is missing.

**Comment by mrmartineau** [comment]
I think you might be right, I think my config was screwed up or something. Cheers for the plugin
