### ISSUE TITLE
About upcoming ESlint v2.0 release (currently RC)

### ISSUE THREAD

**Issue by darkred** [roadhump/SublimeLinter-eslint#118]
Is ESlint 2.0 (currently RC) working in latest SublimeLinter-eslint?
I suppose that 2.0 final will be released within the next few days.

I haven't found any relevant info neither in [the package control page](https://packagecontrol.io/packages/SublimeLinter-contrib-eslint) nor in here.

<br>
_PS. Using ESlint 1.10.3, ST3 dev build 3100 (in win10 x64) and Sublimelinter-eslint 1.9.3._

**Comment by roadhump** [comment]
I didn't try yet, but it seems that there are no any breaking changes in ESLint 2.0, which can break plugin.

**Comment by darkred** [comment]
Thanks for the reply.
v2.0 final was released today, and the package works ok (and shows no errors in console).
