### ISSUE TITLE
globals not being recongize ...

### ISSUE THREAD

**Issue by kkashou** [roadhump/SublimeLinter-eslint#120]
For some reason I am still getting errors regarding my globals when I have it stated to allow them in my .eslintrc file:

![screen shot 2016-02-04 at 8 10 46 pm](https://cloud.githubusercontent.com/assets/8713386/12837856/62fa93a4-cb7b-11e5-9397-0c1c7800ac3c.png)

![screen shot 2016-02-04 at 8 10 33 pm](https://cloud.githubusercontent.com/assets/8713386/12837854/61c3f02a-cb7b-11e5-9eee-dd92d7d896b9.png)

How can I fix this? 

Thanks

**Comment by roadhump** [comment]
You have `jslint` errors, not `eslint`. Disable `jslint` plugin.

**Comment by kkashou** [comment]
How do I disable it since i don't see anything with jslint that makes it activated?

**Comment by kkashou** [comment]
It works perfectly fine now ... really strange.
