### ISSUE TITLE
.eslintignore: Not working with multiple paths in project

### ISSUE THREAD

**Issue by pat841** [roadhump/SublimeLinter-eslint#121]
This is my .eslintignore:
`config.js`

These are my project settings:
![linter](https://cloud.githubusercontent.com/assets/3125126/12864955/58830090-cc6c-11e5-8c23-3efacc736568.png)

For some reason when I have two paths in my project, the .eslintignore doesnt get read and config.js is parsed using eslint. However, if I remove the Logo path so only the Interface path remains, eslint ignore config.js perfectly fine.

Logs with 2 paths:
`SublimeLinter: eslint: config.js ['C:\\Users\\Pat\\Documents\\Work\\Interface\\node_modules\\.bin\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
SublimeLinter: eslint output:
C:\Users\Pat\Documents\Work\Interface\config.js: line 3, col 15, Error - Strings must use singlequote. (quotes)`

Logs with one path:
`SublimeLinter: eslint: config.js ['C:\\Users\\Pat\\Documents\\Work\\Interface\\node_modules\\.bin\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
SublimeLinter: eslint output:
C:\Users\Pat\Documents\Work\Interface\config.js: line 0, col 0, Warning - File ignored because of your .eslintignore file. Use --no-ignore to override.`

eslint version: 1.10.3

**Comment by roadhump** [comment]
It is a limitation of ST itself, so plugin works with `.eslintignore` only if there is one root folder in project. Use project's `.sublimelinterrc` to ignore folders in your case.
