### ISSUE TITLE
Wondering best way to make it work with ESLint 2.0

### ISSUE THREAD

**Issue by johngoren** [roadhump/SublimeLinter-eslint#122]
Ever since the update, I am having trouble Linting.

**Comment by youssmak** [comment]
+1

**Comment by roadhump** [comment]
@johngoren specific details would be nice (debug output). For me eslint 2 works fine.

**Comment by pawelgrzybek** [comment]
@johngoren it works fine for me as well. Probably you don't have an issue with plugin, you have an issue with your config file. Please have a gook at migration to 2.0 guide.

http://eslint.org/docs/user-guide/migrating-to-2.0.0

**Comment by youssmak** [comment]
@roadhump I have the following error

>  Definition for rule 'keyword spacing' was not found

"Keyword spacing" replace "space-return-throw-case" rule in V2

**Comment by johngoren** [comment]
@pawelgrzybek Oh OK, thank you for referring me to that. I seem to get eslint to run OK from the command line, though, but ever since upgrading I can't seem to get SublimeLinter to want to lint anything.

@roadhump I can't see any errors on the SublimeText console, anywhere else I should be looking?

**Comment by roadhump** [comment]
@johngoren So what an output without errors? Enable Tools -> Sublime Linter -> Debug mode and check console.

**Comment by johngoren** [comment]
Yes but just now I toggled it and got it to work. So it seems OK. Sorry about that.
