### ISSUE TITLE
NVM won't load an aliased Node in a new ZSH shell with this plugin.

### ISSUE THREAD

**Issue by stephenhowells** [roadhump/SublimeLinter-eslint#128]
This section of the README seems to render NVM unable to load the currently aliased Node in a new Terminal:

```md
1. If you are using nvm and zsh, ensure that the line to load nvm is in .zprofile and not .zshrc.

2. If you are using zsh and oh-my-zsh, do not load the nvm plugin for oh-my-zsh.
```

The only way to recover Node in the new shell is to run `nvm use default` every time a new shell is opened. Obviously this isn't ideal. I know there are certain complexities with Sublime plugins finding Node with NVM in ZSH. My question is, are there any work arounds to avoid this issue?

**Comment by roadhump** [comment]
Here is the fix https://github.com/roadhump/SublimeLinter-eslint/issues/42

**Comment by stephenhowells** [comment]
Ok thanks! :+1:
