### ISSUE TITLE
eslint filename detection broken on windows (quotes in path)

### ISSUE THREAD

**Issue by phromo** [roadhump/SublimeLinter-eslint#132]
sublimelinter-eslint passes the --stdin-filename argument with double-quotes on Windows, causing the extension detection to fail in eslint.

If you modify linter.py removing the screen_path function introduced in https://github.com/roadhump/SublimeLinter-eslint/commit/610768af60800c0eab5f75d7b783ca36bb2a2bc8 everything works as expected.

I'm running Windows 10 and Sublime Text 3103. Solution tested working also with paths containing spaces and special characters.

**Comment by roadhump** [comment]
I've reverted this commit, it should be done another way.
