### ISSUE TITLE
SublimeLinter cannot read environment variables

### ISSUE THREAD

**Issue by GreenRaccoon23** [roadhump/SublimeLinter-eslint#135]
SublimeLinter doesn't seem to be able to read environment variables. Specifically, it does not seem to read the `$PATH` and `$HOME` variables. Is it supposed to be able to?  

If I install `eslint` locally (in a `package.json`), it works fine. It lints like it should.  

If I am trying to use my global installation of `eslint`, it does not work. After some trial and error, I found out that if I set an absolute path in SublimeLinter's `paths` setting, it works. Like this:  
```
"paths": {
    "linux": [
        "/home/dan/.npm-packages/bin"
    ],
    "osx": [],
    "windows": []
},
```

If I try to use the `$HOME` variable, it does not work. Like this:  
```
"paths": {
    "linux": [
        "$HOME/.npm-packages/bin"
    ],
    "osx": [],
    "windows": []
},
```

It seems odd to me. I should add that I'm using `zsh` and that I'm setting up my `$PATH` string/`$path` array in `.zshenv`, not `.zshrc` or `.zprofile`. I also have the same `$PATH` settings in a `.bashrc` file, just in case. This is correct though because `eslint <file>` from Terminal works (with both `zsh` and `bash`).  

Let me know if I should put this issue in the SublimeLinter repo itself instead.  

#### `SublimeLinter` console output

Help: Check menu item `Tools -> SublimeLinter -> Debug Mode`, then check menu item `View -> Show Console`, then menu item `Tools -> Sublime Linter -> Lint This View`.

```
warning: mnemonic t not found in menu caption Tools
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 258, in on_load_async
    callback.on_load_async(v)
  File "SideBar in /home/dan/.config/sublime-text-3/Installed Packages/SideBarEnhancements.sublime-package", line 70, in on_load_async
  File "/opt/sublime_text_3/sublime.py", line 159, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):55:4
SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
SublimeLinter: ERROR: eslint cannot locate 'eslint' 
SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
SublimeLinter: ERROR: eslint cannot locate 'eslint' 
```

#### `eslint` output from command line

Help: Use the same `eslint` instance which plugin uses (check console output). Run in terminal: 

```
cd your_project_folder
eslint some/file.js # if eslint is global
./node_modules/.bin/eslint some/file.js # if eslint is local
```

```
...
✖ 250 problems (250 errors, 0 warnings)
```

#### Additional info if needed (ST version, OS, configuration)

Sublime Text 3
Linux (Arch Linux)
Zsh

**Comment by benmosher** [comment]
IME on OS X, Sublime in general does not seem to read any shell .*rc files. 

This SO post seems to corroborate: http://stackoverflow.com/a/24311110/344143

**Comment by roadhump** [comment]
@GreenRaccoon23 In general SublimeText and SublimeLinter treat system variables their own way and I am not sure if you can use them in configs (suppose you can't). It is an issue for Sublime Text or Sublime Linter itself, I suppose. I myself use absolute path in `paths`. Also you can try to check here http://www.sublimelinter.com/en/latest/usage.html#how-linter-executables-are-located, probably it will help you to change $PATH somewhere in system and skip SublimeLinter config.

**Comment by laukstein** [comment]
Having the same issue. It seems `"mnemonic": "t"` must be changed to `"mnemonic": "T"`, https://github.com/eddiejessup/Transcrypt/issues/4
