### ISSUE TITLE
Eslint not found in package control

### ISSUE THREAD

**Issue by EasonWang01** [roadhump/SublimeLinter-eslint#136]
Fill your issue here.
![04](https://cloud.githubusercontent.com/assets/11001914/14069733/238490b6-f4d0-11e5-9ea1-4da0fce7383d.png)

**Comment by roadhump** [comment]
Hello, can you do this, go to \%USER%\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\, open the biggest file there as JSON and check by search if `SublimeLinter-contrib-eslint` package is mentioned there

**Comment by EasonWang01** [comment]
Thanks,finally I found I have install it,but this package default will not show in package list.

**Comment by blewa** [comment]
I ran into this issue when I was trying to install this plugin for the first time.

@roadhump  - I wasn't able to find hte package in the list, but it does appear to work properly when I manually git clone the repo in to the plugins directory.

**Comment by gagantaneja** [comment]
try `SublimeLinter-eslint`.It will work.

**Comment by mdmoniskhan** [comment]
@gagantaneja Thanks, it worked!
