### ISSUE TITLE
Does not lint files; syntax error in debug mode

### ISSUE THREAD

**Issue by hmfoster** [roadhump/SublimeLinter-eslint#152]
Eslint works fine through my terminal, but does not lint my files through ST3. I have followed the documentation for both SublimeLinter and SublimeLinter-eslint. I have included the console output I see when running in debug mode below.
#### `SublimeLinter` console output

SublimeLinter: eslint: tes.js ['/Users/haileyfoster/test/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
/Users/haileyfoster/test/node_modules/eslint/lib/cli.js:18
const fs = require("fs"),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/haileyfoster/test/node_modules/eslint/bin/eslint.js:29:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10) 
#### `eslint` output from command line

The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.

/Users/haileyfoster/test/tes.js
  1:1  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  1:1  error  'askdj' is not defined                                                 no-undef
  1:6  error  Trailing spaces not allowed                                            no-trailing-spaces
  1:6  error  Missing semicolon                                                      semi

✖ 4 problems (4 errors, 0 warnings)

```


```

**Comment by hmfoster** [comment]
Found the fix. My system was defaulting to node v0.12.0. Everything works now after changing the default to v6.2.2

**Comment by neverfox** [comment]
I still get `SyntaxError: Use of const in strict mode` with node v6.6.0.

**Comment by neverfox** [comment]
It was pulling 0.10 in because of path issues (much like linter path issues). Moved nvm script to .zprofile and it works.

**Comment by roadhump** [comment]
I think case is closed
