### ISSUE TITLE
SublimeLinter Settings are not in tools, after installing, and restarting

### ISSUE THREAD

**Issue by caub** [roadhump/SublimeLinter-eslint#174]
So I can't even do the: 
- Check menu item `Tools -> SublimeLinter -> Debug Mode`, then check menu item `View -> Show 

step

I'm on ubuntu17.04, sublime text 3126

package control list-packages gives:

![2017-08-24-114907_448x271_scrot](https://user-images.githubusercontent.com/3134574/29660730-53b57610-88c2-11e7-814e-9d1a4aea6fdf.png)

![2017-08-24-123952_921x701_scrot](https://user-images.githubusercontent.com/3134574/29662988-7c2e9c28-88c9-11e7-9080-e354b7329697.png)
![2017-08-24-124003_921x701_scrot](https://user-images.githubusercontent.com/3134574/29662990-7eb2bdbc-88c9-11e7-9644-2369580a5c41.png)

**Comment by caub** [comment]
works better by installing SublimeLinter first

**Comment by sphynxlee** [comment]
how do you solve this problem?
I also met the problem, which "sublimeLinter" doesn't show on tools menu

**Comment by braver** [comment]
There is no solution, SublimeLinter has no entries for the tools menu. Everything is available via settings or the command palette.

**Comment by sphynxlee** [comment]
@braver Thanks a lot. It seems I have to adjust settings to fit my requirement.

**Comment by AALIMRAN** [comment]
HI, @braver could you please help me? everything available via which settings?

**Comment by braver** [comment]
@AALIMRAN open the command palette and enter “SublimeLinter settings”.
