### ISSUE TITLE
Stops working with nodeca plugin

### ISSUE THREAD

**Issue by kjplunkett** [roadhump/SublimeLinter-eslint#20]
SublimeLinter stops linting when I try to use the ESLint plugin <a href="https://www.npmjs.com/package/eslint-plugin-nodeca">Nodeca</a>

Here's my .eslintrc:
{
    "env": {
        "browser": true,
        "node": true
    },
    "plugins":["nodeca"],
    "rules": {
        "quotes": 0,
        "no-underscore-dangle": 0,
        "no-path-concat": 0,
        "valid-jsdoc": 1,
        "no-reserved-keys": 1,
        "block-scoped-var": 1,
        "no-lonely-if": 1,
        "no-nested-ternary": 1,
        "no-multiple-empty-lines": 1,
        "space-after-keywords": [1, "always"],
        "space-before-blocks": [1, "always"],
        "nodeca/indent": [2, "spaces", 4]
    }
}

I know it's just that plugin because it works when I comment these lines out
"plugins":["nodeca"], 
"nodeca/indent": [2, "spaces", 4]

Sublime console in debug mode shows: 
`SublimeLinter: eslint: Grunt.config.js ['/usr/local/bin/eslint', '--format=compact', '--stdin'] `
`SublimeLinter: eslint output:`
`<text>: line 16, col 48, Error - Trailing comma. (no-comma-dangle)`
`1 problem `

But when I put those lines back in to use nodeca, the linter stops working and I get this in the console:
`SublimeLinter: eslint: Grunt.config.js ['/usr/local/bin/eslint', '--format=compact', '--stdin'] `

I know the plugin is installed with node because I see it in my package.json and npm list.

I'm pretty new to front-end development, so any help you can give me would be appreciated! 

Thanks!

**Comment by roadhump** [comment]
Hello

I'm really not into eslint plugins idea now, but it seems you can try to install it globally 

`npm install eslint-plugin-nodeca -g`

**Comment by kjplunkett** [comment]
Thank you!!

That worked :)

Cheers,

*Kris Plunkett*

Engineering Intern  |  Emma®

kris.plunkett@myemma.com

800.595.4401 or 615.292.5888

615.292.0777 (fax)


Emma helps organizations everywhere communicate & market in style.

Visit us online at www.myemma.com
<http://myemma.com/?utm_source=%20EmmaSignatures&utm_medium=%20email&utm_content=text-lin%20k&utm_campaign=EmmaSignatu%20res-email-text-link-home>



Please consider the environment before printing this e-mail

On Wed, Feb 4, 2015 at 12:52 PM, Aliaksei <notifications@github.com> wrote:

> Hello
>
> I'm really not into eslint plugins idea now, but it seems you can try to
> install it globally
>
> npm install eslint-plugin-nodeca -g
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roadhump/SublimeLinter-eslint/issues/20#issuecomment-72914553>
> .
>

-- 
 
<http://marketingunited.com/?utm_source=signature&utm_medium=email&utm_campaign=Signature>
