### ISSUE TITLE
Disable linter if no eslint configuration is found

### ISSUE THREAD

**Issue by tschaub** [roadhump/SublimeLinter-eslint#22]
It looks like this would require a change to `eslint` itself.  But I'm curious if you would support a linter setting that disabled the linter when no configuration was found.

I'm looking for a way to smartly disable the linter when I work with code that doesn't conform to the default `eslint` rules.  I'd like to rely on per-project `.eslintrc` files, and have the linter not run when I open a file for which the configuration cannot be found.

**Comment by roadhump** [comment]
I suppose it should not be concern for this plugin. You should use `.sublimelinterrc` settings to disable specific linters in your project folder http://www.sublimelinter.com/en/latest/settings.html#sublimelinterrc-settings

**Comment by tschaub** [comment]
Right.  I was hoping there could be support for a setting that made linting "opt-in" instead of "opt-out."  Rather than having to go around adding `.sublimelinterrc` files on every directory that doesn't conform to the default `eslint` rules, I'd prefer a plugin setting that only enabled it when a linter configuration was found.

**Comment by sapegin** [comment]
Why this issue was closed? This makes plugin useless because it requires us to put `.sublimelinterrc` to every project that uses jshint. In other words to majority of all projects.

**Comment by roadhump** [comment]
@sapegin I suppose the majority of users install plugin to use it and disable it for special cases. I am not sure, but does SublimeLinter allow to disable linter in main config, but enable it project-specific? Also, there is `--reset` option for ESLint to turn off any rules except `.eslintrc` Configuration, I guess it also can be set in main config of SublimeLinter. As I heard, this option will be turned on by default in ESLint 1.0, I guess it can solve your problem.

**Comment by arturadib** [comment]
> I'm looking for a way to smartly disable the linter when I work with code that doesn't conform to the default eslint rules

Yes, this. Not all projects need eslint, and those that do almost invariably happen to have a `.eslintrc` file. The plugin should by default only kick in if that file is found, otherwise it's extremely annoying.

**Comment by roadhump** [comment]
@arturadib I suggest to use `args: ["--reset"]` in global SublimeLinter config. It makes ESLint apply rules only from project's `.eslintrc`, not any default rules, and if you don't have `.eslintrc`, there will be no any warnings at all. You can set `args: ["--no-reset"]`in project `.sublimelinterrc` if you still need default rules in project. I guess it is a universal solution for your problem.

**Comment by arturadib** [comment]
@roadhump that seems to have done the trick, thank you!

**Comment by arturadib** [comment]
actually that doesn't seem to work on a project that did have an `.eslintrc` – it doesn't apply the rules found in that file

**Comment by roadhump** [comment]
@arturadib Seems working for me. Try to execute in command line in your project `eslint --reset`, it should be equal to what plugin does and it should apply only rules from `.eslintrc`.

**Comment by ramiel** [comment]
`--reset` is not a valid option in eslint 3. The bug is still present. The linter should disable itself if no .eslintrc file is found.

**Comment by javadbat** [comment]
what is the solution for VS code to disable linting for the non-configured project it's really annoying
