### ISSUE TITLE
reserved keyword as error vs warning

### ISSUE THREAD

**Issue by wprater** [roadhump/SublimeLinter-eslint#25]
I'm writing in ES6 module format and since the 'reserved word' is registering as an error, linting will stop. if we switch this to a warning, will this continue linting the doc? 

is there a way for me to do this or ignore this linting error?

**Comment by roadhump** [comment]
You should check `.eslintrc and ESLint itself, it is not an issue for this plugin

**Comment by wprater** [comment]
it's not possible in eslintrc.  my question to you is, how possible would it be to switch this to a warning, and would that make the linting of the doc continue?

**Comment by roadhump** [comment]
Since this plugin is just a convenient way to call `eslint <your file>`, you should create bug for ESLint, there is no way to fix it here.
