### ISSUE TITLE
.eslintignore support

### ISSUE THREAD

**Issue by blinskey** [roadhump/SublimeLinter-eslint#29]
Thanks for the great plugin! Is there any support for `.eslintignore` files? They don't seem to have any effect in Sublime for me, but they're working for eslint on the command line.

**Comment by roadhump** [comment]
Hello, eslint does not apply .eslintignore to separate files, as I know. Means `eslint file.js` will always lint file with any eslintignore settings. Use .sublimelinterrc instead.

**Comment by blinskey** [comment]
I get a warning from eslint on the command line when I try to lint an individual file that's included in `.eslintignore`:

    0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override

 But I'll look into using `.sublimelinterrc`. Thanks!

**Comment by roadhump** [comment]
Plugin runs command similar to `cat file.js | eslint --stdin`, there is no way to use eslintignore too.

**Comment by blinskey** [comment]
Ah, I see. Thanks for the explanation!
