### ISSUE TITLE
Should log fatal errors from eslint

### ISSUE THREAD

**Issue by mamacdon** [roadhump/SublimeLinter-eslint#32]
I accidentally introduced a syntax error into my project's `package.json` file (which I guess is used by eslint to check for config info). This caused linting to silently fail. All my .js files showed "No lint errors" even when they contained obvious problems.

I had to run `eslint` from the command line to find out what was wrong:

```
$ eslint index.js

c:\Users\mamacdon\AppData\Roaming\npm\node_modules\eslint\lib\config.js:59
            throw e;
                  ^
YAMLException: Cannot read config file: c:\Users\mamacdon\code\myproject\package.json
Error: JS-YAML: missed comma between flow collection entries at line 15, column 13:
        "node:" ">=0.12.0"
                ^
```

Can errors from the eslint process be logged to the Sublime console? This would make problem determination much easier when eslint fails.

**Comment by roadhump** [comment]
I guess it is a work for SublimeLinter itself to output plugin's stderr in console too. You should create an issue in SublimeLinter repo.

**Comment by mamacdon** [comment]
It turns out, if I enable `Tools > SublimeLinter > Debug Mode`, I do see the error logged in Sublime's console. So I guess everything is worked as designed here...
