### ISSUE TITLE
Sublime 3 hangs on save with ESLint

### ISSUE THREAD

**Issue by quicksnap** [roadhump/SublimeLinter-eslint#35]
I'm noticing that, upon saving, Sublime 3 will pause for about a second while ESLint does its checking.

Is there a way to make this operation asynchronous so that Sublime won't block?

**Comment by roadhump** [comment]
Plugin doesn't make deal with sync/async, you should post issue to SublimeLinter itself if it seems laggy for you while saving. BTW I never face such issue and have a strong suspicion that there is another reason (plugin or maybe remote file system) for it. Try Tools -> SublimeLinter -> Lint Mode -> Background, it makes linting without saving file.

**Comment by quicksnap** [comment]
Putting it in the background helps, and doesn't block the UI. Thanks! I do prefer only linting on save, but oh well. Thanks again!
