### ISSUE TITLE
Unable to find babel-eslint

### ISSUE THREAD

**Issue by toddself** [roadhump/SublimeLinter-eslint#36]
Installed eslint and babel-eslint globally and locally.

.eslintrc:
```
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0
  }
}
```

Error from sublime-linter:
```
dispatcher.js:

  eslint:
    0: Cannot find module 'babel-eslint'
```

From the command line in the same directory:
```
11:36:57 ~/src/.../src/configurator:master
↳ eslint dispatchers/dispatcher.js
11:37:41 ~/src/.../src/configurator:master
↳
```

**Comment by roadhump** [comment]
Try to restart SublimeText, it seems like a SublimeLinter issue, see #31

**Comment by toddself** [comment]
oh crap.  the one thing i didn't try...

sorry!
