### ISSUE TITLE
Use locally installed eslint if present

### ISSUE THREAD

**Issue by glenjamin** [roadhump/SublimeLinter-eslint#37]
I'm not sure how viable this is, but it would be quite useful.

To ensure all devs are using the same linter version, and to allow us to keep the right plugins installed, we install eslint as a devDependency in our project.

It would be good if the plugin is able to spot that `node_modules/.bin/eslint` is present in a project, and use that instead of the global executable.

What do you think?

**Comment by roadhump** [comment]
Plugin already works with eslint front `package.json` if there is any, see README and latest closed issues.

**Comment by glenjamin** [comment]
Ah, this is because I have nested `package.json`s, with eslint in the upper one. Will discuss the issue on the SublimeLinter side.

Thanks

**Comment by mderazon** [comment]
I think that it should only use eslint locally if it is explicitly written as a dependency in package.json, and not just look in the `node_modules/.bin` for eslint. Otherwise we get issues like https://github.com/roadhump/SublimeLinter-eslint/issues/31#issuecomment-119725202
