### ISSUE TITLE
Support for nested .eslint files?

### ISSUE THREAD

**Issue by fhemberger** [roadhump/SublimeLinter-eslint#38]
I'm working on a Node.js project, which also includes client side code. All general rules are set in the `.eslintrc` file in the project's root, client side rules (e.g. jQuery env) are stored in `client/.eslintrc`:

```
├── client
│   ├── client.js
│   └── .eslintrc
└── .eslintrc
```

When I run the `eslint` CLI command, rules in `client/.eslintrc` are processed correctly, however in Sublime Text, those rules don't seem to be applied.

Tested with eslint v0.16.1 and v0.18 (running on io.js v1.6.2), latest SublimeLinter-eslint, Sublime Text 3 Build 3082 (Dev Channel)

**Comment by fhemberger** [comment]
Sorry, seems to have been a hiccup in Sublime Text.

**Comment by willlma** [comment]
I'm having this issue. Do you remember how you resolved it?

**Comment by fhemberger** [comment]
Simply restarting ST worked for me at that time.
