### ISSUE TITLE
SublimeLinter-contrib-eslint removed from Package Control

### ISSUE THREAD

**Issue by sethen** [roadhump/SublimeLinter-eslint#39]
I was running my latest dotfiles repo and it appears that SublimeLinter-contrib-eslint has been removed from Package Control in Sublime Text 3.

**Comment by sethen** [comment]
This has been resolved.

**Comment by kaste** [comment]
`sublimelinter-contrib-eslint` has been renamed to just `sublimelinter-eslint`. If it doesn't show up for 'install' you may have it already (yes, this happens!)
