### ISSUE TITLE
Pass current filename to eslint to enable `context.getFilename()`

### ISSUE THREAD

**Issue by tikotzky** [roadhump/SublimeLinter-eslint#40]
This is related to #28 

eslint now supports a `--stdin-filename` option which allows you to pass the filename to enable rules which use `context.getFilename()`.
See: https://github.com/eslint/eslint/pull/2326

I dont know too much about how sublime linter works but can sublime linter be updated to pass the filename to eslint?

**Comment by zertosh** [comment]
@roadhump This would be awesome! :+1:

**Comment by roadhump** [comment]
Will update plugin in package manager when next ESLint version is released.

**Comment by zertosh** [comment]
Thanks @roadhump!

**Comment by tikotzky** [comment]
Awesome! 👍

**Comment by zertosh** [comment]
@roadhump eslint v0.20.0 was released with support for `--stdin-filename`. https://github.com/eslint/eslint/releases/tag/v0.20.0

**Comment by roadhump** [comment]
Done in https://github.com/roadhump/SublimeLinter-eslint/releases/tag/1.4.0

**Comment by zertosh** [comment]
Thanks @roadhump. You've got a trailing comma in `messages.json` that's causing the messages not to load - https://github.com/roadhump/SublimeLinter-eslint/blob/613896f/messages.json#L6

**Comment by roadhump** [comment]
Thanks @zertosh , just fixed it
