### ISSUE TITLE
ERROR: eslint cannot locate 'eslint' 

### ISSUE THREAD

**Issue by Spentacular** [roadhump/SublimeLinter-eslint#42]
I know I'm probably just missing something stupid, but I can't seem to get eslint to work unless I install it within the directory I'm working in. I'm getting these two errors:

```
SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
SublimeLinter: ERROR: eslint cannot locate 'eslint' 
```

I'm currently using `nvm`, and I have `source ~/.nvm/nvm.sh` in my `.zshenv` file. I can also get it to load in my $PATH in my console, `eslint -v` works just fine, but I can't seem to get it to load in Sublime. It also doesn't look like it's in my $PATH when Sublime loads:

```
SublimeLinter: computed PATH using /bin/zsh:
/usr/local/bin
/usr/local/sbin
/Users/spentacular/.rbenv/shims
/Users/spentacular/.bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

Is there something just completely dumb I'm missing? I've restarted Sublime multiple times, reinstalled everything, I just can't get it to reference the global copy. Thanks!

**Comment by uipoet** [comment]
Try `which eslint`, then paste that path up to the `bin` in your `Sublime Linter.sublime-settings`.

Mine looks like this:

```JSON
"paths": {
   "osx": [
    "/usr/local/opt/nvm/versions/io.js/v1.8.1/bin"
  ]
},
```

**Comment by Spentacular** [comment]
@uipoet Thanks so much! That worked perfectly. I'm using iojs as well and I was worried that may be apart of the problem, but this worked perfect!

**Comment by alexserver** [comment]
@uipoet thanks, your tip helped me too.

**Comment by dkudrin** [comment]
@uipoet thank you for tip!

**Comment by Aggie123** [comment]
thanks! works for my case
