### ISSUE TITLE
Invalid option '--stdin-filename' - perhaps you meant '--stdin'? 

### ISSUE THREAD

**Issue by dshook** [roadhump/SublimeLinter-eslint#43]
I believe the latest version bump of this package broke linting.

Turning on debug mode of Sublime linter I get this in the console
```
SublimeLinter: eslint: search.js ['C:\\dev\\search-stream\\node_modules\\.bin\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
Invalid option '--stdin-filename' - perhaps you meant '--stdin'? 
```

However if I run eslint in powershell
`cat .\lib\search.js | eslint --format compact --stdin --stdin-filename '@'`
It works fine.

This is on windows with these libs
node v0.12.1
SublimeLinter-eslint 1.4.1 
SublimeLinter 3.4.39
babel-eslint@3.0.1
eslint@0.20.0
npm@2.5.1

**Comment by pbeshai** [comment]
Also happens to me on Mac OS X.
node v0.10.36
SublimeLinter-contrib-eslint v1.4.1
SublimeLinter v3.4.39

**Comment by zertosh** [comment]
@pbeshai It's [new in eslint 0.20.0](http://eslint.org/blog/2015/04/eslint-0.20.0-released/). you have to update your eslint.

**Comment by pbeshai** [comment]
@zertosh Thanks so much. Felt like I was coding blind for a while today. :+1:

**Comment by dshook** [comment]
And with that hint, I found that the local reference to eslint in package.json was out of date but the global one was not. Thanks

**Comment by PTaylour** [comment]
@pbeshai :+1: I can see again!

**Comment by roadhump** [comment]
Strange, plugin should check eslint version, if it can't check version of local package, maybe you should post bug to SublimeLinter itself.






Best Regards,Aliaksei Shytkin

**Comment by ptim** [comment]
:+1:  @dshook updating the local dep solved it for me - tx!

**Comment by vvo** [comment]
Too bad you have to spend time dealing with this issue. I have a local eslint in a project and nothing was shown, no error from sublime-linter.

Until you activate the linter debug in sublime options then you see this message, search github etc..

How could we have had a backward compatible sublimelinter-eslint? Dunno.
