### ISSUE TITLE
.eslintignore is not working

### ISSUE THREAD

**Issue by voronianski** [roadhump/SublimeLinter-eslint#44]
I'm not sure is that a right place for an issue. I have such `.eslintrc` file:

```javascript
// http://eslint.org/docs/rules
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true
  },
  "plugins": [
    "react"
  ],
  "rules": {
    "strict": 0,
    "quotes": [2, "single"],
    "no-underscore-dangle": 0,
    "no-unused-vars": 1,
    "no-unused-expressions": 0,
    "react/jsx-no-undef": 2
  }
}
```

And `.eslintignore` in the root folder with one line:

```
lib/**/*.js
```

However files in the `lib` folder are still linted and highlighted with warnings in Sublime..

**Comment by roadhump** [comment]
Plugin does not execute `eslint` in the directory of file and it does not use its `.eslintignore`. Copy your ignore settings to `.sublimelinterrc`
```
{
    "linters": {
        "eslint": {
            "excludes": ["lib/**/*.js"]
        }
  }
}
```

**Comment by voronianski** [comment]
@roadhump thanks!
