### ISSUE TITLE
obey .eslintignore settings

### ISSUE THREAD

**Issue by clintwood** [roadhump/SublimeLinter-eslint#46]
Using this plugin together with [`babel-sublime`](https://github.com/babel/babel-sublime) as per this excellent article [Lint Like It’s 2015](https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48) by Dan Abramov!

What would be great is if the linter obeyed `.eslintignore` settings as per the [documentation](http://eslint.org/docs/user-guide/configuring).  I'm assuming that it is not using the ignore file because code is passed to `eslint` via `stdin`.

I took a tiny look into this and it looks like one would have to lint using the `tmpfile` method rather than using `stdin` when executing the linter `cmd`.  Perhaps then it would obey the `.eslintignore` setttings.

**Comment by roadhump** [comment]
This issue gave me a thought to create an issue for ESLint https://github.com/eslint/eslint/issues/2432 which should allow to check `.eslintignore` in plugin.

**Comment by clintwood** [comment]
@roadhump, thanks for looking into this!

**Comment by roadhump** [comment]
Fixed in #49, waiting for new eslint version to make a release
