### ISSUE TITLE
Invalid option '--stdin-filename' - perhaps you meant '--stdin'? 

### ISSUE THREAD

**Issue by jasonslyvia** [roadhump/SublimeLinter-eslint#47]
It use to work like a charm, but somehow it stop working and output following log in Sublime's console:

````
SublimeLinter: eslint: ipush.js ['/usr/local/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
Invalid option '--stdin-filename' - perhaps you meant '--stdin'? 
````

I've tried reinstall `sublimelinter-contrib-eslinter` in Sublime Text, it doesn't help.

eslint: v0.18.0
node: v0.10.31
OS: OS X 10.10.2
Sublime Text: v3 build 3083

**Comment by roadhump** [comment]
See #43
