### ISSUE TITLE
How to disable eslint for HTML files?

### ISSUE THREAD

**Issue by playpauseandstop** [roadhump/SublimeLinter-eslint#62]
Is there a way to disable `SublimeLinter-eslint` from linting inline JS code in HTML files?

I'm really out of ideas here, as even `<script>/* eslint-disable */</script>` has no effect.

Any suggestions?

**Comment by roadhump** [comment]
Seems ok for me 
```html
<head>
    <script>
        /* eslint-disable */
        var a = 33;
    </script>
</head>
```

`/*eslint-disable*/` should be set in the each `<script>` block, SublimeLinter processes each block separately.
