### ISSUE TITLE
JSX: Error - Unexpected token <

### ISSUE THREAD

**Issue by fzzzt** [roadhump/SublimeLinter-eslint#68]
espree 2.0.4
eslint 0.24.0

I am getting this error in SublimeLinter-contrib-eslint. In the console it seems to be running but I'm not 100% sure that my config is being applied and that is resulting in this error, so I'm not sure if it's my linter config, SublimeLinter config, or what. The console logs the following (the [...] are my replacing of long paths):

    SublimeLinter: eslint: MyView.jsx ['[...]\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
    SublimeLinter: eslint output: [...]MyView.jsx: line 3, col 11, Error - Unexpected token <

Code:

    var MyView = React.createClass({
    	render: function() {
    		return (<div>Coming Soon!</div>);
    	}
    });

My SublimeLinter configuration:

    "default": {
        [...]
        "linters": {
            "eslint": {
                "env": {
                    "browser": true,
                    "jquery": true
                },
                "ecmaFeatures": {
                    "jsx": true
                }
            }
        },
    }

I guess the first question is: _should_ this `eslint` configuration work, assuming SublimeLinter is working properly? Any other hints as to what might be wrong?

**Comment by fzzzt** [comment]
Running `eslint` on the command-line with a `.eslintrc` file in that folder works, so there seems to be a problem with my configuration and getting that passed to `eslint`.

**Comment by roadhump** [comment]
You should use only `.eslintrc` configuration with plugin, SublimeLinter configuration does not allow add `.eslintrc` config there.

**Comment by fzzzt** [comment]
Okay. Is there a way to specify a path to a `.eslintrc` file on the command-line from the SublimeLinter config? Or use some sort of default path

**Comment by fzzzt** [comment]
Ah it looks like `args` might be what I need.

**Comment by cleechtech** [comment]
I am getting this same error in Sublime Text. What is the fix?

**Comment by roadhump** [comment]
@cleechtech You should configure `eslint` to understand JSX http://eslint.org/docs/user-guide/configuring#specifying-language-options (`jsx: true`)

**Comment by cleechtech** [comment]
Ok thank you @roadhump
