### ISSUE TITLE
searching 'eslint' in package control does not find 'SublimeLinter-contrib-eslint'

### ISSUE THREAD

**Issue by StJohn3D** [roadhump/SublimeLinter-eslint#69]
Lots of 'SublimeLinter-contrib-*' but no eslint :(

**Comment by roadhump** [comment]
Are you sure you don't have it installed already?

**Comment by StJohn3D** [comment]
-smh- And that would explain why it suddenly started working after I uninstalled js-lint
Sorry about that.
