### ISSUE TITLE
Global .eslintrc file?

### ISSUE THREAD

**Issue by BenRKarl** [roadhump/SublimeLinter-eslint#70]
Not so much of an issue but more of a question: is it possible for this plugin to recognize a .eslintrc file saved somewhere other than in the project root. For example if I wanted to have a single config applied to all my projects without having to copy it to the project root each time. I tried saving it in my user root folder, which is above my projects, but it was not recognized and default rules were applied. Many thanks!

**Comment by glebec** [comment]
Seconded. It would be nice if we could, say, make a `.eshintrc` file and drop it in the `User` folder of package control. If `.eshintrc` was found in the directory tree it would use that, otherwise default to the provided file.

**Comment by roadhump** [comment]
@BenRKarl `.eslintrc` in user home folder seems working for me, can you check it again, please?

@glebec I guess `.eslintrc` in user home folder (of projects folder) is the solution of your problem, see http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

**Comment by glebec** [comment]
Thanks @roadhump

**Comment by BenRKarl** [comment]
@roadhump @glebec I did indeed get it working, but I had to update my SublimeLinter User settings so that the "rc_search_limit" was set to null. Previously it was set to 2 and I think that may have been what was preventing it from searching high enough to find the file in my user home.

Thank you for the help and response!

**Comment by B4bharat** [comment]
@BenRKarl I set the "rc_search_limit" to null as well in my user settings, but its not helping me in my case on my Ubuntu 14.04 LTS, please help

**Comment by iplus26** [comment]
@glebec Sorry, I still don't get it after reading the [eslint docs](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy).

Could I just put a .eslintrc.* file into, let's say, `~/Library/Application Support/Sublime Text 3/Packages/User/`, aka, the User folder of Package Control, for global usage?

**Comment by glebec** [comment]
@iplus26 — no, place your config file in your home folder (`~`).

**Comment by iplus26** [comment]
Thanks, @glebec 

Though I prefer to put the global rc file under User folder of Package Control, so that I can sync the User folder among different accounts or computers, I guess that's the only way to use it globally so far. I really appreciate it, thanks again.
