### ISSUE TITLE
global .eslintignore?

### ISSUE THREAD

**Issue by snadn** [roadhump/SublimeLinter-eslint#71]
Is there a global .eslintignore can be used?

I just want to use eslint in my work dir. But i don't know how to set.

**Comment by roadhump** [comment]
Probably this https://github.com/roadhump/SublimeLinter-eslint#i-want-to-use-custom-rules-global-eslintignore-file-etc

**Comment by snadn** [comment]
thanks. My problem has been solved.

But in windows. '"~/.eslintignore" invalid and should be "${home}/.eslintignore" instead of.
