### ISSUE TITLE
.eslintrc ignored in Sublime

### ISSUE THREAD

**Issue by asyncmax** [roadhump/SublimeLinter-eslint#72]
Running `eslint` as a command finds `.eslintrc` at my project root very well. But in Sublime, `eslint` seems unable to find it. (I'm using Sublime 3083 Windows version.)

I found this problem occurs only when I have only one folder in my project.

I guess the conversion to relative path in `linter.py`, after detecting `__RELATIVE_TO_FOLDER__`, is the root cause of this problem. It appears that this code assumes CWD is set to the only one folder in my project, which doesn't look like the case.

**Comment by roadhump** [comment]
Hello, try this https://github.com/roadhump/SublimeLinter-eslint#contextgetfilename-in-rule-returns-relative-path
