### ISSUE TITLE
error if local eslint is in sibling directory of js directory

### ISSUE THREAD

**Issue by janusch** [roadhump/SublimeLinter-eslint#73]
Sublime Linter cannot find eslint if it is installed locally in node_modules which is a sibling dir to the scripts dir.
Inside the node_modules dir linting works just fine, but as soon as I try to link the other js files eslint is not found anymore. 

I fixed it by installing it globally for now, though i would prefer to have it installed locally. Is there an `args` option to remove the option to use relative file paths and still use it with a local eslint install?

Thanks for all the great work on this plugin!

**Comment by roadhump** [comment]
Hello, does not it work for you https://github.com/roadhump/SublimeLinter-eslint#contextgetfilename-in-rule-returns-relative-path?

**Comment by binarytales** [comment]
I have the same issue and the config option does not work for me.

It looks like when setting that option `--stdin-filename'` is being set twice. See this from my console:

````
SublimeLinter: eslint: admin.js ['/Users/jon/Work/QBooks/recipe-display/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__', '--stdin-filename', '@']
````

When I manually edit this line in `lint.py` to

````
cmd = ('eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@')
````

Everything starts working as expected but I'm not using an ignore file which it looks like the change to `__RELATIVE_TO_FOLDER__` was intended to support.

Interestingly on an older project of mine where I have `eslint:^0.24.0` and `babel-eslint: ^3.1.20` installed locally linting is still working as expected with the latest version SublimeLinter-eslint

Hope this information helps finding a fix for this.

**Comment by roadhump** [comment]
@binarytales It's very strange, second option should just rewrite first, I can't see how they can be a reason. Do you have one or several root folders in your project?

**Comment by roadhump** [comment]
@binarytales Also, does it just output nothing in ST console in SublimeLinter debug mode?

**Comment by binarytales** [comment]
@roadhump I have just one root folder in my project. 

In a project running an old version of eslint I see a `SublimeLinter: eslint output:` line in the console (followed by appropriate errors) 

In a project running the latest version (but same code) I see the line initiating the command but no output.

**Comment by janusch** [comment]
Hey,
thanks for the debugging help. Sadly I still have problems getting it resolved.

here is the console output:

1. the dir besides the dir that contains the local eslint (eslint not working):
´ SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary´
´SublimeLinter: ERROR: eslint cannot locate 'eslint'´

2. the folder that contains node_modules and local eslint:
´SublimeLinter: eslint: karma.conf.js ['/build_tools/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__', '--stdin-filename', '@']´

If eslint and plugins are installed globally it works fine. I'd just prefer to have it local. 
Could there be a workaround for this issue, or maybe the solution would be to move the ´node_modules´ dir up to being ancestor of scripts folder?
maybe this helps? I would love to get this resolved!

Thanks for your help!

**Comment by roadhump** [comment]
@janusch 

Let's start by example
If you want to use local eslint, your project folder (let's call it `ProjectFolder`) should look like
```
/node_modules (eslint here)
/folder
index.js
package.json
```

So, when you do `subl /path/to/ProjectFolder` or open `ProjectFolder` in sublime text any other way, plugin will lint `index.js` and any other js files in folders inside using local `eslint` if any, otherwise global `eslint`. It does not depend (at least it must not) if you set `---stdin-filename` to `@` or not. 

It also works for cases if you open parent or child folder (`subl /path/to/ProjectFolder/folder` or `subl /path/to`). It will find closest parent `package.json` and `node_modules` and will use its `eslint`. It seems working, I just check it.

So, is there something that does not work correct for you?

**Comment by janusch** [comment]
@roadhump thank you very much for your reply!

my directory structure is as follows:

´´´
ProjectFolder
    /scriptsFolder
    /buildToolsFolder
        /node_modules
        .eslintc
        package.json
```

So, inside the ´buildToolsFolder´ linting is working just fine with local config.
Inside ´scriptsFolder´ it cannot find ´.eslintrc´ and the relevant ´node_modules´.

Is there any way to point to the ´buildToolsFolder´ when it is a sibling folder of the scriptsFolder to get linting to work?

Alternatively, I must use global esLint and plugins to get linting to work, or move ´node_modules´ and
´.eslintrc´ above ´scriptsFolder´?

Looking at your example again, if ´node_modules´ and ´.eslintrc´ are within the ´scriptsFolder´ would that resolve the issue?

Thanks again for helping me to get this resolved!!!

**Comment by roadhump** [comment]
@janush Your `eslint` and `eslintrc` instances should be in the same or ancestor folder of file. I suppose you should create `package.json` and install `eslint` inside your `scriptsFolder`.

**Comment by janusch** [comment]
@roadhump thanks for clearing that up. I think i will change the directory structure so everything works, since there is no way in checking in a sibling directory. I know it is a convention in the npm world, I gota go with the flow.

Thanks for your help!
