### ISSUE TITLE
Can't find the plug in in package control

### ISSUE THREAD

**Issue by ciaoben** [roadhump/SublimeLinter-eslint#74]
Hi, 
I simply cannot find the plug in in package control:

![schermata 2015-08-03 alle 15 35 18](https://cloud.githubusercontent.com/assets/4526061/9038552/5f47c5be-39f5-11e5-8798-6fd2ab59108d.png)

**Comment by roadhump** [comment]
Hello, are you sure you don't have it already installed?

**Comment by ciaoben** [comment]
@roadhump yeah, I am a newbie yes, but not at this point :smile: later today I am going to complete remove sublime and reinstall it, and let you know if change something

**Comment by aemonge** [comment]
I can't see it neither /:

**Comment by sorawit** [comment]
I also can't see it.

**Comment by aemonge** [comment]
It did was installed, but there's no easy test to see if it's already installed. @sorawit maybe you're missing the babel plugin. At least that was the case for me, hope It helps

**Comment by ianstormtaylor** [comment]
Also can't see it :(

**Comment by stefancrain** [comment]
Missing for me also

**Comment by philstrong** [comment]
command palette
Package Control: Add respository
https://github.com/roadhump/SublimeLinter-eslint

command palette
Install Package
eslint -> select it

**Comment by stefancrain** [comment]
@philstrong That worked for me. Can you do a PR to update the README.md for the others? If you are busy I'd be glad to do it.

**Comment by NeXTs** [comment]
@philstrong thank you

**Comment by ajmichels** [comment]
Doesn't seem like this is an issue anymore.
