### ISSUE TITLE
Lag while save files

### ISSUE THREAD

**Issue by floydsoft** [roadhump/SublimeLinter-eslint#75]
Hi,

This package works well while editing the code, but when I save the file, it's always lag around 2 seconds, is there anyway to fix it?

Thanks!

**Comment by floydsoft** [comment]
After took a little investigation, it seems the same issue as https://github.com/SublimeLinter/SublimeLinter3/issues/267

**Comment by floydsoft** [comment]
A workaround:

I finally adopt this PR https://github.com/SublimeLinter/SublimeLinter3/pull/271

and cancel the `Show Errors on Save` in `Tools/SublimeLinter`, it works fine for me.

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/SublimeLinter3/pull/271 has been merged, thank you for your patience.

Hope this resolves this issue.
