### ISSUE TITLE
ESLint columns now 1-based

### ISSUE THREAD

**Issue by faergeek** [roadhump/SublimeLinter-eslint#76]
Since version 1.0.0 ESLint migrated from 0-based to 1-based column numbers
http://eslint.org/blog/2015/07/eslint-1.0.0-released/#breaking-changes-100-rc-1

So errors highlighted a bit weird now:
![Image of Yaktocat](https://leto3f.storage.yandex.net/rdisk/f2b65bbb9d9432480d7880a87a74b0681f44f085226f83fac124d23421ad954e/inf/cGUzF9NdKELS2ToM6OzdxU3AlHnX-eC4LA2Yovw7g8mdRU9BLKblrYoogPmMY6pKHbvO7VNzhrtbfufjnVJ2Dw==?uid=0&filename=2015-08-09%2011-19-22%20users.js%20%E2%80%94%20react-users-crud.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=0f5c6050748404c448a974b4adf250c1&force_default=no&ycrid=na-0e1158c934ec6d75d6625c99bd2653a5-downloader7g)

**Comment by roadhump** [comment]
Thank you, fixed in version 1.6.0
