### ISSUE TITLE
Background lint mode causes 100% CPU usage on each keystroke

### ISSUE THREAD

**Issue by klapec** [roadhump/SublimeLinter-eslint#77]
Every time I type something in the file I'm working on, a `node` process comes up for a second and takes 100% of the CPU. This has to be ESLint running in the background. Is this extremely high CPU usage caused by ESLint itself or is there something that can be done within SublimeLinter or SublimeLinter-eslint?

In comparison, Atom's linter-eslint takes only 25-30% of the CPU.

**Comment by roadhump** [comment]
There were performance improvements in SublimeLinter lately (#75), is this issue still relevant?

This plugin does not run `eslint` in background, it runs `eslint` from time to time (on save or change file). Try to run `eslint` from command line and check CPU usage there, probably `eslint` causes it.

**Comment by kdanninger** [comment]
Hmm, still happening to me. 800% every time i save

**Comment by kdanninger** [comment]
![screen shot 2016-04-11 at 1 38 08 pm](https://cloud.githubusercontent.com/assets/792464/14436449/b97e2986-ffea-11e5-86df-055a28cac2da.png)

**Comment by kdanninger** [comment]
I feel like there's a bug with the "Lint Mode". I've set it to Manual, and now it's just constantly just stuck at 800%... :( i reeeeeally don't want to switch to atom. halp plz

**Comment by kdanninger** [comment]
hey @roadhump, false alarm!! After letting the linter do it's thing for 20 minutes, it calmed down... now it only consumed 70-90% when saving.. which i can live with! 

Thanks for your hard work!
