### ISSUE TITLE
Presence of .eslintrc halting linting

### ISSUE THREAD

**Issue by BenRKarl** [roadhump/SublimeLinter-eslint#78]
Starting this morning configurations from my .eslintrc file saved in my root have stopped being applied. What's more is that it seems to have stopped linting all together. When I remove the file it works with the default options, but when I put it back it stops linting. No idea what the problem could be, any advice is greatly appreciated.

**Comment by roadhump** [comment]
I've updated min version of ESLint to 1.0.0, probably it caused some mess with plugin. Update ESLint and restart ST can help.

**Comment by BenRKarl** [comment]
Indeed I had not updated ESLint. Once I upgraded to 1.1.0 I was able to get it working. Thanks @roadhump closing this.
