### ISSUE TITLE
Crash on lint - Node problems?

### ISSUE THREAD

**Issue by louwers** [roadhump/SublimeLinter-eslint#79]
I have been trying to solve this issue for far too long now, so I figured it'd be best to ask here what might be the problem.

Initially I tried to follow [this guide](https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48) to get babel-eslint to work, but I now found out that even plain `SublimeLinter-eslint` crashes Sublime Text whenever I try to lint something.

Eslint is installed locally, whenever I try `./node_modules/.bin/eslint test.js` in my shell it works brilliantly. I enabled SublimeLinter debugging, and judging from the console eslint seems to be loaded normally:

`SublimeLinter: eslint: test.js ['/Users/Bart/Desktop/test/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] `

I suspect that node might be causing problems, because a package like `SublimeLinter-cppcheck` does not cause problems (installed via brew) while `SublimeLinter-jshint` gives me the same problem (jshint is also installed through npm). However, I have added the path where node is installed to my SublimeLinter settings, and I don't know what else I can do.

My settings look like this:

```
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "load/save",
        "linters": {
            "eslint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [
                "/usr/local/bin/node"
            ],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```
my `.eslintrc` cannot be the problem.

**Any help is much appreciated!**

**Comment by louwers** [comment]
I have opened a topic on StackOverflow as well. http://stackoverflow.com/questions/32177497/sublimelinter-crashes-sublime-text-with-linters-installed-via-npm

**Comment by roadhump** [comment]
What crash does it cause? ST exits?

**Comment by louwers** [comment]
Thanks for your reply! ST froze...
Very weird, but I have since deleted the StackOverflow question, a clean install did the trick.

The problem must have been on my side, it works brilliantly now.
