### ISSUE TITLE
Do I still need SublimeLinter-jshint if I use this linter?

### ISSUE THREAD

**Issue by littlee** [roadhump/SublimeLinter-eslint#82]
I install `npm install -g eslint`
I install `SublimeLinter-contrib-eslint`
But when I open a jsx file, it still uses jshint not eslint, how do I fix this?
![qq 20150902181911](https://cloud.githubusercontent.com/assets/7534668/9633046/42967aac-51bd-11e5-856d-b4b47dc043ec.png)

**Comment by roadhump** [comment]
I suppose you just have SublimeLinter-jshint plugin installed. Remove or disable it.

**Comment by littlee** [comment]
Something changed after I remove SublimeLinter-jshint,
But it still can not work with jsx syntax
![qq 20150903173941](https://cloud.githubusercontent.com/assets/7534668/9655332/edcebff6-5262-11e5-858d-6be47d397e4f.png)

**Comment by roadhump** [comment]
Check Tools - SublimeLinter - Debug Mode. I suppose you need to  add `jsx` option to `.eslintrc` http://eslint.org/docs/user-guide/configuring#specifying-language-options

**Comment by littlee** [comment]
where should I put the `eslintrc` file?
when I type `eslint --init` from CMD, it generate `.eslintrc` file in the current directiry.

**Comment by roadhump** [comment]
it should be enough, just check if you have option `jsx`

**Comment by littlee** [comment]
Thanks, I get it eventually.

**Comment by littlee** [comment]
@roadhump 
Excuse me, it's me again,
can this linter use a global `.eslintrc` file so that I don't have to run `eslint --init` in every project?

**Comment by roadhump** [comment]
@littlee Yes, plugin works with configs as `eslint` itself http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy
