### ISSUE TITLE
Linting in HTML syntax lints all <script> blocks whether they are JavaScript or not

### ISSUE THREAD

**Issue by durz** [roadhump/SublimeLinter-eslint#83]
Currently all `<script>` blocks in a HTML document are linted as though they are JavaScript. There are, however, very valid use cases for `<script>` blocks to *not* contain JavaScript. This is very common in libraries that support templating.

For example, when using Kendo UI, HTML templates are inserted inside of script blocks with a specific value for the `type` attribute (`text/x-kendo-tmpl`). 

````
<script type="text/x-kendo-tmpl">
    <tr data-uid="#= uid #">
        <td>...</td>
    </tr>
</script>
````
With SublimeLinter-eslint, the contents get treated as JS so, naturally, the linter reports errors like:

> Unexpected token <

The HTML5 spec for the script element does not impose limits on the value of the `type` attribute, aside from requiring it to be a valid MIME type: http://www.w3.org/TR/html5/scripting-1.html#scriptingLanguages

SublimeLinter-jshint/JSHint handles this by only linting script blocks which have either a `type` attribute with a value of `"text/javascript"`, or no `type` attribute at all. This is consistent with modern browser's handling of script tags where unknown script types get ignored: https://developer.mozilla.org/en/docs/Web/HTML/Element/script#attr-type.

Can the linter be configured to behave this way? Perhaps even by using something like [eslint-plugin-html](https://www.npmjs.com/package/eslint-plugin-html)?

**Comment by roadhump** [comment]
@durz JSHint itself has a functionality to lint HTML files and extract content of `script` tags (by `--extract` option). ESLint does not have such option, it lints only JavaScript by files or stdin. It is a SublimeLinter itself, that extracts content of `script` tags for ESLint or any other JS linters. I suppose you should create bug for SublimeLinter, there is no way to solve it with this plugin.

**Comment by TremayneChrist** [comment]
Could be to do with this issue #87

**Comment by grotewold** [comment]
No real news yet, waiting on a "hopeful" fix to the HTML scoping.

https://github.com/SublimeLinter/SublimeLinter3/issues/356
https://github.com/sublimehq/Packages/issues/106
