### ISSUE TITLE
incompatibility with last eslint version ?

### ISSUE THREAD

**Issue by barroudjo** [roadhump/SublimeLinter-eslint#84]
In debug mode, sublime-linter gives me:
````
SublimeLinter: eslint output:
Invalid option '--stdin-filename' - perhaps you meant '--stdin'?
````
That seems to be a compatibilty issue...

**Comment by barroudjo** [comment]
I can confirm the issue is there, once I removed '--stdin-filename' from linter.py everything worked fine.

**Comment by barroudjo** [comment]
I can confirm the issue is there, once I removed '--stdin-filename' from linter.py everything worked fine.

**Comment by roadhump** [comment]
Please, check FAQ https://github.com/roadhump/SublimeLinter-eslint#plugin-still-does-not-work-or-there-are-errors-in-st-console

**Comment by barroudjo** [comment]
That was actually the issue, my project local version of eslint was outdated, and I thought (wrongly) that the global version was used.

Thanks
