### ISSUE TITLE
highlight full string content?

### ISSUE THREAD

**Issue by benmosher** [roadhump/SublimeLinter-eslint#89]
See https://github.com/benmosher/eslint-plugin-import/issues/51 for context, but suffice it to say:

when a string literal node is reported (i.e. wrong `quotes` style, be it single or double), only the first quotation mark is highlighted:

![screen shot 2015-09-10 at 11 45 11 am](https://cloud.githubusercontent.com/assets/3709196/10028295/9821b7c6-6139-11e5-9e5b-f856719de0e4.png)

It would be more compelling if the warning surrounded the full string value, quote-to-quote, IMO.

AFAICT, ESLint only provides the column number and not the full span of the reported issue, so is this something you could adjust at the SublimeLinter integration level?

(FWIW: IDEA+PyCharm exhibit the same behavior. so maybe this is the most correct/expected behavior. it just isn't intuitive, from my perspective)

Thanks! 😄

**Comment by roadhump** [comment]
Sorry, but this is impossible in plugin if eslint itself does not produce range of error instead of single position.
