### ISSUE TITLE
.eslintrc with side-by-side folders?

### ISSUE THREAD

**Issue by Dylan-Chapman** [roadhump/SublimeLinter-eslint#92]
I have two folders within my WAMP's www folder that have .eslintrc files. Say, folder1 and folder2. For some reason, when I have folder2 loaded in as a project in Sublime, folder1's .eslintrc file with affect the linting on folder2's files? Is this correct behavior? If so, is there a way to avoid it? Within folder1 and folder2, I would like to use their root .eslintrc files respectively, not mix them.

**Comment by roadhump** [comment]
It's strange, can you try if this will help https://github.com/roadhump/SublimeLinter-eslint#contextgetfilename-in-rule-returns-relative-path ?

**Comment by Dylan-Chapman** [comment]
Looks like that fixed it. Strange! Not sure what that just did.
I appreciate it!
