### ISSUE TITLE
Can I add/change rules via my SublimeLinter.sublime-settings file?

### ISSUE THREAD

**Issue by EyePulp** [roadhump/SublimeLinter-eslint#93]
Howdy - I'm trying to figure out how to exclude or change rules in my **`SublimeLinter.sublime-settings`** file.  I'm looking at https://github.com/eslint/eslint#configuration for the structure, but it's not working.

Here's where I'm at:
```json
    "user": {
        "linters": {
            "eslint": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "rules": {
                    "no-multi-comp": [0,""]
                }
            },
        }
    }
```

**Comment by roadhump** [comment]
Rules should be in `.eslintrc` config file, not in linter settings. You can only add command line options of `eslint` here https://github.com/roadhump/SublimeLinter-eslint#i-want-to-use-custom-rules-global-eslintignore-file-etc

**Comment by EyePulp** [comment]
perfect - thanks.
