### ISSUE TITLE
docs upgrade

### ISSUE THREAD

**Issue by ORESoftware** [roadhump/SublimeLinter-eslint#94]
can you please update your readme.md file to describe how to run the linter on command as well as everytime you save a file or perhaps every 3 seconds?

**Comment by ORESoftware** [comment]
perhaps a mention of this

http://www.sublimelinter.com/en/latest/lint_modes.html

it took me too long to find that... :(

**Comment by roadhump** [comment]
There is a link to SublimeLinter docs in readme already, I don't think such details as lint modes should be mentioned here, it is easier to get full info about SublimeLinter features on its own site.

**Comment by ORESoftware** [comment]
ok np
