### ISSUE TITLE
Error when using local version

### ISSUE THREAD

**Issue by OliverJAsh** [roadhump/SublimeLinter-eslint#98]
I'm using a local version of the `eslint` package, and although the plugin actually appears to work, I get this error in my console:

```
SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
SublimeLinter: ERROR: eslint cannot locate 'eslint' 
```

**Comment by roadhump** [comment]
Hello, did you follow steps from https://github.com/roadhump/SublimeLinter-eslint#faq-and-troubleshooting ?

**Comment by OliverJAsh** [comment]
That works, thank you. Sorry!
